# -*- coding: utf-8 -*-
"""Even.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZ5x_g55McPDBSeb7IkLVI7uZh01gFxO
"""

list = [1,2,3,5,6,7,8,9]
res= [i for i in list if i % 2 == 0]
print("Even numbers",res)